<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                          => __DIR__ . '/Module.php',
    'Application\Controller\CreatePharController' => __DIR__ . '/src/Application/Controller/CreatePharController.php',
    'BuildPharFilterIterator'                     => __DIR__ . '/src/Application/Controller/CreatePharController.php',
    'ApplicationTest\CreatePharControllerTest'    => __DIR__ . '/tests/CreatePharControllerTest.php',
    'ApplicationTest\ModuleTest'                  => __DIR__ . '/tests/ModuleTest.php',
);
