<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                     => __DIR__ . '/Module.php',
  'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Plugin\MeetupClientPlugin'  => __DIR__ . '/src/Application/Plugin/MeetupClient.php',
  'Application\tests\IndexControllerTest'  => __DIR__ . '/tests/IndexControllerTest.php',
  'Application\tests\ModuleTest'           => __DIR__ . '/tests/ModuleTest.php',
);
